spring:
  datasource:
    # url
    url: jdbc:mysql://'mysql 호스트 주소':3306/JUPOZA?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # user
    username: 'id'
    # password
    password : 'password'
    # mysql-driver connector
    driver-class-name: com.mysql.cj.jdbc.Driver
