spring:
  datasource:
    url: jdbc:mysql://jupoza.c7chsemepe5s.ap-northeast-2.rds.amazonaws.com:3306/JUPOZA?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password : jupoza123
    driver-class-name: com.mysql.cj.jdbc.Driver
